# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-PayPal
version:      0.03
version_from: PayPal.pm
installdirs:  site
requires:
    CGI:                           0
    Digest::MD5:                   0
    Net::SSLeay:                   1.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
